name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - linux-gcc
        - linux-clang
        - macos
        include:
        - build: linux-gcc
          os: ubuntu-20.04
          cc: gcc
        - build: linux-clang
          os: ubuntu-20.04
          cc: clang
        - build: macos
          os: macos-10.15

    env:
      CI_TARGET_ARCH: ${{ matrix.arch }}
      CC: ${{ matrix.cc }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ci/actions-install.sh
    - name: Build
      run: ./ci/actions-build.sh
    - name: Smoke test
      run: ./ci/actions-smoke-test.sh
    - name: Full test
      run: ./ci/actions-full-test.sh
